-- =============================================
-- Script Template
-- =============================================
CREATE TABLE tf_deltant_pd_fc  (
    pd_auftr_id        BIGINT        NOT NULL,
    pd_fehl_typ        INTEGER        NOT NULL,
    pd_fehler_txt      NVARCHAR(512),
    pd_dnst_nr         NVARCHAR(3)     NOT NULL,
    pd_tae_beauf       INTEGER,
    pd_tae_durch       INTEGER,
    pd_veranl_stl      INTEGER,
    pd_rks_id          INTEGER,
    pd_schul_abschl    INTEGER,
    pd_geschlecht      INTEGER,
    pd_leist_art_1     INTEGER,
    pd_leist_art_2     INTEGER,
    pd_beh_1           INTEGER,
    pd_beh_2           INTEGER,
    pd_beh_3           INTEGER,
    pd_beh_4           INTEGER,
    pd_anzahl_pt       SMALLINT,
    pd_eing_dat        SMALLDATETIME  NOT NULL,
    pd_abschl_dat      SMALLDATETIME  NOT NULL,
    pd_abschl_art      INTEGER        NOT NULL,
    pd_abschl_grund    INTEGER,
    pd_gez             INTEGER,
    pd_lz		       INTEGER,
    pd_create_dat      SMALLDATETIME  NOT NULL,
    pd_update_dat      SMALLDATETIME  NOT NULL,
    bps_bild_abs	   INTEGER,
    pd_lpe             INTEGER,
    pd_lap             INTEGER,
	pd_bkb_id	       INTEGER,
    [pd_dgk_id]		   INTEGER,
	[pd_spr_id]        INT,
	[pd_trg_schl]      NVARCHAR (10),
    bi_load_date       NCHAR(15)       NOT NULL,
    bi_load_filename   NVARCHAR(256)   NOT NULL
) WITH ( DATA_COMPRESSION = PAGE );
